### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [2]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call `dir()` on `np.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [27]:
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

2. What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [ ]:
#car = string; mpg = float; horsepower = float; origin = string
#after converting to np array, all would be changed to string

3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
#When we import numpy as np, we are importing the package numpy. We call it np for brevity and to reduce type errors. We import numpy to be able to do more sophisticated and efficient calculations on larger data sets.

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [14]:
np_car = np.array(car)
print(type(np_car))
print(np_car.shape)
#This means it is a numpy array with 1 dimension

print(type(np.array(mpg)))
print(np.array(mpg).shape)
#This is the same becuase thre are 406 cars (rows) and one column for each of the arrays

<class 'numpy.ndarray'>
(406,)
<class 'numpy.ndarray'>
(406,)


5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [25]:
np_mpg = np.array(mpg)
print(np_mpg)
print() #Blank line

#Multiply by 12
mltply_mpg = np_mpg*12
print(mltply_mpg)
print()

#divide by 3
dvd_mpg = np_mpg/3
print(dvd_mpg)
print()

#raise to the power of 4
pwr_mpg = np_mpg**4
print(pwr_mpg)
print()

#sqrt mpg
sqrt_mpg = np_mpg**.5 #Could also numpy.sqrt(np_mpg)
print(sqrt_mpg)
print(sqrt_mpg.shape)

[18.  15.  18.  16.  17.  15.  14.  14.  14.  15.   0.   0.   0.   0.
  0.  15.  14.   0.  15.  14.  24.  22.  18.  21.  27.  26.  25.  24.
 25.  26.  21.  10.  10.  11.   9.  27.  28.  25.  25.   0.  19.  16.
 17.  19.  18.  14.  14.  14.  14.  12.  13.  13.  18.  22.  19.  18.
 23.  28.  30.  30.  31.  35.  27.  26.  24.  25.  23.  20.  21.  13.
 14.  15.  14.  17.  11.  13.  12.  13.  19.  15.  13.  13.  14.  18.
 22.  21.  26.  22.  28.  23.  28.  27.  13.  14.  13.  14.  15.  12.
 13.  13.  14.  13.  12.  13.  18.  16.  18.  18.  23.  26.  11.  12.
 13.  12.  18.  20.  21.  22.  18.  19.  21.  26.  15.  16.  29.  24.
 20.  19.  15.  24.  20.  11.  20.  21.  19.  15.  31.  26.  32.  25.
 16.  16.  18.  16.  13.  14.  14.  14.  29.  26.  26.  31.  32.  28.
 24.  26.  24.  26.  31.  19.  18.  15.  15.  16.  15.  16.  14.  17.
 16.  15.  18.  21.  20.  13.  29.  23.  20.  23.  24.  25.  24.  18.
 29.  19.  23.  23.  22.  25.  33.  28.  25.  25.  26.  27.  17.5 16.
 15.5 14.5 22.  22. 

6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [42]:
np_horsepower = np.array(horsepower)
print(sum(np_horsepower))
print()
print(min(np_horsepower))
print()
print(max(np_horsepower))
print()
print(np.median(np_horsepower))
print()
from scipy import stats
print(stats.mode(np_horsepower))

42033.0

0.0

230.0

93.5

ModeResult(mode=array([150.]), count=array([22]))


7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [67]:
print(acceleration[0:5])#print elements in index0 to index 5
print(acceleration[::2])#print elements in all indices, counting by twos

[12.  11.5 11.  12.  10.5]
[12.  11.  10.5  9.  10.  17.5 11.  11.   8.   9.5 15.  15.5 14.5 17.5
 17.5 15.  15.  18.5 15.5 19.  13.  15.5 15.5 11.5 13.  12.  13.5 15.
 14.  19.5 19.  19.  15.5 23.5 16.5 12.  13.  11.  13.5 13.5 14.  14.
 18.  18.  17.  15.  13.  13.  12.5 12.  14.5 11.  16.5 16.  16.  14.
 13.  15.  19.5 13.5 14.  13.  19.5 14.  11.  13.5 16.5 16.  19.  21.
 17.  16.5 14.5 16.  16.5 14.5 19.  15.5 15.  16.  16.  19.5 14.  13.5
 18.5 19.  13.5 16.  16.  13.5 17.  14.  15.  14.5 17.5 16.9 17.7 13.
 13.9 15.4 17.6 22.2 14.2 17.7 16.2 12.2 16.4 15.7 21.9 16.7 12.  14.
 14.8 15.5 12.5 13.7 16.4 17.7 11.1 12.2 14.5 18.2 17.  16.4 14.5 13.5
 14.4 18.6 15.5 12.8 18.2 15.4 17.2 16.7 15.1 13.4 13.7 14.2 14.5 16.7
 14.9 13.6 15.8 16.6 18.2 18.2 15.4 13.2 14.9 15.  14.  14.4 20.1 24.8
 13.2 19.2 16.  12.9 14.7 15.5 16.5 20.1 15.8 17.5 15.2 14.4 21.7 19.9
 13.8 18.  11.4 15.1 17.  16.4 12.6 16.9 16.1 19.4 16.  16.2 14.2 14.4
 14.8 20.4 19.6 13.8 19.  16.6 18.6 16.2 18.  20.5 18.2 

8. Show how to select the number `99` in the array below. 

In [136]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

print(select_99.shape)

(2, 3)


In [47]:
select_99[1,2]
print(select_99[1,2])

99


9. Select the last element in each subarray (do this with one operation.)

In [50]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [51]:
select_more[:,2]#all rows, column 3 is index 2


array([3, 6, 9])

10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [206]:
#np.lookfor('log')
#print()
print(np.log(np_mpg))


[2.89037176 2.7080502  2.89037176 2.77258872 2.83321334 2.7080502
 2.63905733 2.63905733 2.63905733 2.7080502        -inf       -inf
       -inf       -inf       -inf 2.7080502  2.63905733       -inf
 2.7080502  2.63905733 3.17805383 3.09104245 2.89037176 3.04452244
 3.29583687 3.25809654 3.21887582 3.17805383 3.21887582 3.25809654
 3.04452244 2.30258509 2.30258509 2.39789527 2.19722458 3.29583687
 3.33220451 3.21887582 3.21887582       -inf 2.94443898 2.77258872
 2.83321334 2.94443898 2.89037176 2.63905733 2.63905733 2.63905733
 2.63905733 2.48490665 2.56494936 2.56494936 2.89037176 3.09104245
 2.94443898 2.89037176 3.13549422 3.33220451 3.40119738 3.40119738
 3.4339872  3.55534806 3.29583687 3.25809654 3.17805383 3.21887582
 3.13549422 2.99573227 3.04452244 2.56494936 2.63905733 2.7080502
 2.63905733 2.83321334 2.39789527 2.56494936 2.48490665 2.56494936
 2.94443898 2.7080502  2.56494936 2.56494936 2.63905733 2.89037176
 3.09104245 3.04452244 3.25809654 3.09104245 3.33220451 3.13549

11. You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [75]:
unique_origin = np.unique([origin]) #finds the unique items in the column for origin
print(unique_origin) #prints them

['Europe' 'Japan' 'US']


12. 
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [205]:
weight_g = [10.5, 20.3, 12.3, 16.8, 20.3]
svl_cm = [5.2, 30.5, 6.3, 8.1, 28.7]
species = ['d_punctatus', 'c_coluber', 's_dekayi', 'c_coluber', 't_sirtalus']
tail_cm = [2.1, 7.3, 2.5, 3.3, 6.5]

np_weight_g = np.array(weight_g)
np_svl_cm = np.array(svl_cm)
np_species = np.array(species)
np_tail_cm = np.array(tail_cm)

#1 dimensional
print(np_weight_g.shape)
print(np_weight_g.ndim)
print()

#standard 2d array

# _2d_array = np.array([[0, 2, 4, 4], [7, 4, 3, 5]])
# print (_2d_array.shape)
# print(_2d_array.ndim)
# print()

#2-dimensional, column_stack changes the 2 rows of 1-dimensional arrays into 2 columns of 1 dimensional arrays
np_species_weight = np.array([[np_species],[np_weight_g]])
print(np_species_weight)
print()
new_np_species_weight = np.column_stack(np_species_weight)
print(new_np_species_weight.shape)
print(new_np_species_weight.ndim)

#3-dimensional
np_species_svl_weight = np.array([[np_species], [np_svl_cm],[np_weight_g]])
print(np_species_svl_weight)
print()
print(np_species_svl_weight.shape)
print(np_species_weight.ndim)

#4-dimensional
np_all = np.array([[[np_species], [np_svl_cm], [np_tail_cm], [np_weight_g]]])
print(np_all)
print(np_all.shape)
print(np_all.ndim)


(5,)
1

[[['d_punctatus' 'c_coluber' 's_dekayi' 'c_coluber' 't_sirtalus']]

 [['10.5' '20.3' '12.3' '16.8' '20.3']]]

(1, 10)
2
[[['d_punctatus' 'c_coluber' 's_dekayi' 'c_coluber' 't_sirtalus']]

 [['5.2' '30.5' '6.3' '8.1' '28.7']]

 [['10.5' '20.3' '12.3' '16.8' '20.3']]]

(3, 1, 5)
3
[[[['d_punctatus' 'c_coluber' 's_dekayi' 'c_coluber' 't_sirtalus']]

  [['5.2' '30.5' '6.3' '8.1' '28.7']]

  [['2.1' '7.3' '2.5' '3.3' '6.5']]

  [['10.5' '20.3' '12.3' '16.8' '20.3']]]]
(1, 4, 1, 5)
4


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [128]:
#print(origin)

print(origin == 'US')

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True False  True  True  True
 False False False False False False  True  True  True  True  True False
  True False  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False  True False  True False  True  True  True  True  True
  True  True  True  True  True  True False  True  True  True  True False
 False False False  True False False  True False  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True False  True False False  True
  True False  True  True False False False False  True False False  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True False False False False False  True False False
 False False False  True  True  True  True  True  T

14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [132]:
print([np_car[origin == 'US']])

[array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout 

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [184]:
#a square matrix with 1s on the diagonal

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

2. Transpose the following array. 

In [104]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

#this is a 3:3, so the resulting transposed array will still be a 3x3 but with the numbers in different locations

In [183]:
print(transpose_me)
print()
#swap x and y axis
transposed = np.transpose(transpose_me)
print(transposed)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


3. Why does this multiplication operation fail? 

In [186]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:
#multiplying an array with 3 rows by an array with 2 rows, unless it was the identity matrix (matrix multiplication rules)

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

In [194]:
print(horsepower[origin =='Europe'])
print()
print("Average horsepower European cars:") 
print(np.average(horsepower[origin =='Europe']))

[115.  46.  87.  90.  95. 113.  48.  90.  70.  76.  60.  54. 112.  76.
  87.  69.  46.  90.  49.  75.  91. 112. 110.  83.  67.  78.  75.  75.
  67.  71.  70.  95.  88.  98. 115.  86.  81.  83.  70.  71. 102.  88.
 120.  58.  78.  78. 110.  48. 103. 125. 115. 133.  71.  71.  77.  71.
  69.  76.  78.  48.  48.  67.  67.   0.  62.  88.  74.   0.  80. 110.
  76.  74.  52.]

Average horsepower European cars:
78.78082191780823


5. On average are Japanse cars more fuel efficient than US cars? 

In [195]:
#print(np_mpg[origin == 'Japan'])
print("Average mpg of Japanese cars:")
print(np.average(np_mpg[origin =='Japan']))
print()
print("Average mpg of USA made cars:")
print(np.average(np_mpg[origin =='US']))
print()
print ('No, the average fuel economy of Japanese made cars is 30.4mpg, the average fuel economy of US made cars is 19.6mpg')

Average mpg of Japanese cars:
30.450632911392404

Average mpg of USA made cars:
19.688188976377955

No, the average fuel economy of Japanese made cars is 30.4mpg, the average fuel economy of US made cars is 19.6mpg


6. What is the correlation coefficient of `mpg` and `weight`?

In [180]:
np.corrcoef(np_mpg, weight)

#This is an array of the R values. There is a negative correlation of 0.787, meaning that they are about 79% inversely correlated

array([[ 1.        , -0.78750994],
       [-0.78750994,  1.        ]])

7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [ ]:
# a np.array() allows you to do many more calculations a lot faster and more efficiently than in a list

In [ ]:
# a list could be preferred when you want to be able to keep multiple data types since in a np.array() they will allbe converted to the same type